#+AUTHOR:    Cayetano Santos
#+LANGUAGE:  en
#+DESCRIPTION: Example emacs configuration
#+OPTIONS:   H:3 num:nil toc:2

* Table of Contents                                 :TOC:
:PROPERTIES:
:VISIBILITY: all
:END:

- [[#usage][Usage]]
- [[#example-configuration-file][Example configuration file]]
  - [[#variables][Variables]]
  - [[#ancillary-packages][Ancillary packages]]
  - [[#eglot][Eglot]]
  - [[#vhdl][Vhdl]]

* Usage

Within Emacs, run =M-x org-babel-tangle= to extract source code out of this file to =/$TMPDIR/emacs.d/init.el=. This example code may be used as Emacs [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html][init file]] when starting Emacs as

#+begin_src sh :tangle no
  export TMPDIR=/tmp; emacs --init-directory=$TMPDIR/.emacsd.d
#+end_src

It assumes =/$TMPDIR/emacs.d/= as =user-emacs-directory= to avoid overwritting the default user directory. You may modify this location by temporary re declaring =$TMPDIR=.

You may check =ghdl= capabilities as =lsp= with help of an example project:

#+begin_src sh :tangle no
  git clone --depth=1 https://gitlab.com/csantosb/ip/alu alu
#+end_src

This example has been tested under GNU/Emacs 29.4. It assumes =ghdl-ls= is in your =PATH=, and privileges built-in Emacs packages.

* Example configuration file
:PROPERTIES:
:header-args: :tangle (format "%s/%s" (getenv "TMPDIR") ".emacs.d/init.el") :mkdirp yes
:END:

** Variables

Setup necessary variables.

#+begin_src emacs-lisp
  (setq use-package-always-defer t)
#+end_src

** Ancillary packages

*** Flymake

Flymake is a modern on-the-fly syntax checking extension for GNU Emacs.

#+begin_src emacs-lisp
  (use-package flymake
    :hook
    (prog-mode . flymake-mode))
#+end_src

*** Eldoc

#+begin_src emacs-lisp
  (use-package eldoc
    :custom
    (eldoc-echo-area-prefer-doc-buffer t)
    (eldoc-documentation-strategy 'eldoc-documentation-compose-eagerly))
#+end_src

** Eglot

#+begin_src emacs-lisp
  (use-package eglot
    :config
    (push '(vhdl-mode "ghdl-ls") eglot-server-programs)
    :custom
    ;; activate Eglot in cross-referenced, non-project
    (eglot-extend-to-xref t))
#+end_src

** Vhdl

#+begin_src emacs-lisp
  (use-package vhdl-mode
    :ensure nil ; built-in
    :mode (("\\.\\(vhd\\(?:l?\\)?\\)" . vhdl-mode))
    :hook (vhdl-mode . (lambda()
                         (when (and (executable-find "ghdl-ls")
                                    (locate-dominating-file
                                     default-directory "hdl-prj.json"))
                           (eglot-ensure)))))
#+end_src

* Advanced

For a more advanced example, see [[https://git.sr.ht/~csantosb/emacs.vhdl-ide][here]].
